import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../Components/Hero";
import SiteLayout from "../Components/SiteLayout";
import TeamMemberContainer from "../Components/TeamMemberContainer";

const Home: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>FragStack Hybrid</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <SiteLayout>
        <Hero />
        <TeamMemberContainer />
      </SiteLayout>
    </>
  );
};

export default Home;
